services:
  cats_dogs_api:
    image: ghcr.io/himajajaddu/mlops_assignment_2:latest
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/cats_dogs_model.pt
      - DEVICE=cpu
    volumes:
      - ${MODEL_DIR:-../models}:/app/models